"-",
":",
"a",
"al",
"como",
"con",
"de",
"del",
"desde",
"e",
"el",
"en",
"entre",
"habia",
"hasta",
"la",
"las",
"le",
"lo",
"los",
"mas",
"no",
"o",
"por",
"que",
"se",
"ser",
"sera",
"su",
"sus",
"tambien",
"tras",
"un",
"una",
"y",
"ya"